export enum EmitEventType {
  UPDATE_STATE
}

//自定义事件名称
export enum PublishEventType {
  CARD_PUBLISH = 'CARD_PUBLISH',
  APP_PUBLISH = 'APP_PUBLISH'
}

export const playStateKey = 'PlayStateKey'


//appstorage_key

//persistenceV2键
export const SONG_KEY = 'PERSISTENCE_SONG_KEY'
export const LOGIN_KEY = 'LOGIN_KEY'
export const COLOR_MODE_KEY = 'COLOR_MODE_KEY'
export const ENABLE_DARK_MODE_KEY = 'ENABLE_DARK_MODE_KEY'
export const IS_FOLLOW_SYSTEM_SETTING_KEY = 'IS_FOLLOW_SYSTEM_SETTING_KEY'
export const NICK_IMAGE_KEY = 'NICK_IMAGE_KEY'
